### ISSUE TITLE
Microbial Fraction

### ISSUE THREAD

**Issue by Naturalist1986** [wwood/singlem#167] opened 2024-02-28 07:42 UTC
Hi,

I'm trying to use singlem to assess the percentage of eukaryotes in a metagenome. For this I have generated an artificial metagenome derived from known fungal and bacterial genomes. I have encountered several issues:

1. Why does the profile file exclude the eukaryotes, even though they are found in the otu table?
2. When running microbial_fraction I get 18% of bacteria even though they compose 87% of the reads?

Thanks

**Comment by wwood** [comment] 2024-03-11 21:41
Hi,

Apologies for the slow response, have been travelling.

1. The issue is that the marker genes used are not single copy in eukaryotes. Therefore when converting an OTU table to a taxonomic profile, OTUs that are Eukaryote are removed, since it is hard to reason about them. Right now SingleM only targets bacteria and archaea, and eukaryote sequences are only included so that they don't get incorrectly assigned to bacteria or archaea.

2. That seems not good. I'm curious about this case, because it might point to issues in microbial_fraction - I assume you've already accounted for the difference in genome sizes when working out the percentages. Or put another way, do you see the 87% of reads mapping to bacteria when mapping e.g. with CoverM ?

Thanks, ben

**Comment by Naturalist1986** [comment] 2024-03-12 09:35
Hi Ben,

Sorry for not updating sooner, but there was a mistake in my data, I have since tested singlem on new simulated data and it is amazingly accurate: 

![unnamed](https://github.com/wwood/singlem/assets/136818404/6c1cd27f-f077-486a-b62b-56f99054f1c3)

We are really curious how you calculate the eukaryote percentage without identifying the sequences. 
Thanks!

**Closed** 2024-03-12 10:08 UTC
