### ISSUE TITLE
AttributeError: 'module' object has no attribute 'run_many'

### ISSUE THREAD

**Issue by xvazquezc** [wwood/singlem#11] opened 2016-06-23 00:14 UTC
Tried with v 0.6.0 and 0.6.1. Memory allocated 20GB, used <2GB

Command:
```
singlem pipe --sequences 028-LFA*R1*.fastq.gz --otu_table 028-LFA_otu_table.csv --threads 12
```
Log:
```
06/23/2016 10:00:26 AM INFO: Using as input 4 different sequence files e.g. 028-LFA_S1_L001_R1_001.fastq.gz
06/23/2016 10:00:26 AM INFO: Searching for reads matching 30 different protein HMMs
06/23/2016 10:09:29 AM INFO: Finished search phase
06/23/2016 10:09:29 AM INFO: Running separate alignments in GraftM..
Traceback (most recent call last):
  File "/home/z3382651/bin/singlem/bin/singlem", line 327, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 118, in run
    align_result = self._align(search_result)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 564, in _align
    extern.run_many(commands, num_threads=self._num_threads)
AttributeError: 'module' object has no attribute 'run_many'
```

Any idea what can be wrong?

**Comment by wwood** [comment] 2016-06-23 00:18
Looks like an outdated version of extern is installed, maybe? These issues will be fixed when I get around to making a proper package and submitting it to pip, but I'm not there yet.

**Comment by xvazquezc** [comment] 2016-06-23 00:58
Could be... I upgraded extern and the error changed:
```
06/23/2016 10:47:51 AM INFO: Using as input 4 different sequence files e.g. 028-LFA_S1_L001_R1_001.fastq.gz
06/23/2016 10:47:51 AM INFO: Searching for reads matching 30 different protein HMMs
06/23/2016 10:56:27 AM INFO: Finished search phase
06/23/2016 10:56:27 AM INFO: Running separate alignments in GraftM..
06/23/2016 10:56:55 AM INFO: Finished extracting aligned sequences
06/23/2016 10:56:55 AM INFO: Running taxonomic assignment with graftm..
Traceback (most recent call last):
  File "/home/z3382651/bin/singlem/bin/singlem", line 327, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 145, in run
    extracted_reads, graftm_assignment_method)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 589, in _assign_taxonomy
    extern.run_many(commands, num_threads=1)
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/extern/__init__.py", line 70, in run_many
    return runner.run(commands, progress_stream=progress_stream)
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/extern/multi_runner.py", line 89, in run
    raise extern.ExternCalledProcessError(*res[2:])
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28  --threads 12 --forward /scratch/4291393.katana.science.unsw.edu.au/singlem.028-LFA_S1_L002_R1_001.Xe0fBK.fasta /scratch/4291393.katana.science.unsw.edu.au/singlem.028-LFA_S1_L001_R1_001.sFG0bn.fasta /scratch/4291393.katana.science.unsw.edu.au/singlem.028-LFA_S1_L004_R1_001.04SSA9.fasta /scratch/4291393.katana.science.unsw.edu.au/singlem.028-LFA_S1_L003_R1_001.pw5kS5.fasta --graftm_package /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE --output_directory /dev/shm/tmpGwfZu6/graftm_aligns/4.09.ribosomal_protein_L5_rplE --assignment_method pplacer returned non-zero exit status 1.
STDERR was: Traceback (most recent call last):
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/bin/graftM", line 345, in <module>
    Run(args).main()
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/graftm/run.py", line 526, in main
    self.graft()
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/graftm/run.py", line 371, in graft
    filter_minimum
UnboundLocalError: local variable 'filter_minimum' referenced before assignment
STDOUT was: 
```

**Comment by wwood** [comment] 2016-06-23 01:00
Ah, yes. That's an error that occurs with an old version of GraftM. Are you at 0.9.5 ?

**Comment by xvazquezc** [comment] 2016-06-23 01:01
Yes, I got an old version (0.9.4). It's bee a while since last time I used it.
I'll try again.

**Comment by xvazquezc** [comment] 2016-06-23 01:26
Updated, but I got an error again:
```
06/23/2016 11:22:42 AM INFO: Using as input 4 different sequence files e.g. 028-LFA_S1_L001_R1_001.fastq.gz
06/23/2016 11:22:42 AM INFO: Searching for reads matching 30 different protein HMMs
Traceback (most recent call last):
  File "/home/z3382651/bin/singlem/bin/singlem", line 327, in <module>
    known_sequence_taxonomy = args.known_sequence_taxonomy)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 108, in run
    search_result = self._search(hmms, forward_read_files)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 520, in _search
    run(hmms, graftm_protein_search_directory, True)
  File "/home/z3382651/bin/singlem/bin/../singlem/pipe.py", line 512, in run
    extern.run(cmd)
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/extern/__init__.py", line 41, in run
    stdout)
extern.ExternCalledProcessError: Command graftM graft --verbosity 2 --input_sequence_type nucleotide  --min_orf_length 96   --filter_minimum 28 --threads 12 --forward 028-LFA_S1_L001_R1_001.fastq.gz 028-LFA_S1_L002_R1_001.fastq.gz 028-LFA_S1_L003_R1_001.fastq.gz 028-LFA_S1_L004_R1_001.fastq.gz --search_only --search_hmm_files /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE/graftmyMs8Yt_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE/graftmTfJ6Ql_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.19.ribosomal_protein_S12_S23.gpkg.spkg/4.19.ribosomal_protein_S12_S23/graftm0jUili_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.19.ribosomal_protein_S12_S23.gpkg.spkg/4.19.ribosomal_protein_S12_S23/graftmkDMHbw_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.18.ribosomal_protein_S10_rpsJ.gpkg.spkg/4.18.ribosomal_protein_S10_rpsJ/graftm__FSnc_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.18.ribosomal_protein_S10_rpsJ.gpkg.spkg/4.18.ribosomal_protein_S10_rpsJ/graftmjrbRZd_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.15.ribosomal_protein_S2_rpsB.gpkg.spkg/4.15.ribosomal_protein_S2_rpsB/graftmwIz0De_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.15.ribosomal_protein_S2_rpsB.gpkg.spkg/4.15.ribosomal_protein_S2_rpsB/graftmKdLlZz_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.10.ribosomal_protein_L6_rplF.gpkg.spkg/4.10.ribosomal_protein_L6_rplF/graftmQNplv3_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.10.ribosomal_protein_L6_rplF.gpkg.spkg/4.10.ribosomal_protein_L6_rplF/graftmmXEyAR_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.08.ribosomal_protein_L3_rplC.gpkg.spkg/4.08.ribosomal_protein_L3_rplC/graftm9H24vO_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.08.ribosomal_protein_L3_rplC.gpkg.spkg/4.08.ribosomal_protein_L3_rplC/graftmTpYyQM_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.21.ribosomal_protein_S19_rpsS.gpkg.spkg/4.21.ribosomal_protein_S19_rpsS/graftmmuWy_P_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.21.ribosomal_protein_S19_rpsS.gpkg.spkg/4.21.ribosomal_protein_S19_rpsS/graftmK2Qzj9_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.12.ribosomal_protein_L11_rplK.gpkg.spkg/4.12.ribosomal_protein_L11_rplK/graftmsR8moo_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.12.ribosomal_protein_L11_rplK.gpkg.spkg/4.12.ribosomal_protein_L11_rplK/graftmgyqgXl_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.07.ribosomal_protein_L2_rplB.gpkg.spkg/4.07.ribosomal_protein_L2_rplB/graftmIi9ipp_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.07.ribosomal_protein_L2_rplB.gpkg.spkg/4.07.ribosomal_protein_L2_rplB/graftmbdiWA2_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.13.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/4.13.ribosomal_protein_L14b_L23e_rplN/graftmzhRzmq_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.13.ribosomal_protein_L14b_L23e_rplN.gpkg.spkg/4.13.ribosomal_protein_L14b_L23e_rplN/graftmnYiuII_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.16.ribosomal_protein_S5.gpkg.spkg/4.16.ribosomal_protein_S5/graftmqKtHTs_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.16.ribosomal_protein_S5.gpkg.spkg/4.16.ribosomal_protein_S5/graftmpuZ5Di_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.11.ribosomal_protein_L10.gpkg.spkg/4.11.ribosomal_protein_L10/graftmJ13IRm_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.11.ribosomal_protein_L10.gpkg.spkg/4.11.ribosomal_protein_L10/graftmYvtMa9_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.14.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/4.14.ribosomal_protein_L16_L10E_rplP/graftmEN3gBL_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.14.ribosomal_protein_L16_L10E_rplP.gpkg.spkg/4.14.ribosomal_protein_L16_L10E_rplP/graftms5tUZU_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.20.ribosomal_protein_S15P_S13e.gpkg.spkg/4.20.ribosomal_protein_S15P_S13e/graftme1EtU3_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.20.ribosomal_protein_S15P_S13e.gpkg.spkg/4.20.ribosomal_protein_S15P_S13e/graftmT1CGO9_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.17.ribosomal_protein_S7.gpkg.spkg/4.17.ribosomal_protein_S7/graftmhq3Ygj_search.hmm /home/z3382651/bin/singlem/singlem/../db/4.17.ribosomal_protein_S7.gpkg.spkg/4.17.ribosomal_protein_S7/graftmNHyRbc_search.hmm --output_directory /dev/shm/tmpjHjA4w/graftm_protein_search --aln_hmm_file /home/z3382651/bin/singlem/singlem/../db/4.09.ribosomal_protein_L5_rplE.gpkg.spkg/4.09.ribosomal_protein_L5_rplE/graftmyMs8Yt_search.hmm  returned non-zero exit status 1.
STDERR was: /share/apps/python/2.7.9/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py:61: GtkWarning: gdk_cursor_new_for_display: assertion `GDK_IS_DISPLAY (display)' failed
  cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
Traceback (most recent call last):
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/bin/graftM", line 39, in <module>
    from graftm.run import Run
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/graftm/run.py", line 13, in <module>
    from graftm.create import Create
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/graftm/create.py", line 17, in <module>
    from graftm.tree_cleaner import TreeCleaner
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/graftm/tree_cleaner.py", line 1, in <module>
    import skbio.tree
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/skbio/__init__.py", line 14, in <module>
    import skbio.io  # noqa
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/skbio/io/__init__.py", line 236, in <module>
    import_module('skbio.io.format.clustal')
  File "/share/apps/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/skbio/io/format/clustal.py", line 151, in <module>
    from skbio.alignment import TabularMSA
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/skbio/alignment/__init__.py", line 207, in <module>
    from ._tabular_msa import TabularMSA
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/skbio/alignment/_tabular_msa.py", line 20, in <module>
    from skbio._base import SkbioObject, MetadataMixin, PositionalMetadataMixin
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/skbio/_base.py", line 20, in <module>
    import matplotlib.pyplot as plt
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/home/z3382651/bin/mypythondir/mypythonenv/mypythonenv/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 61, in <module>
    cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
RuntimeError: could not create GdkCursor object
STDOUT was: 
```

**Comment by wwood** [comment] 2016-06-23 01:32
This is an unfortunate error caused by scikit-bio. The problem I believe is a lack of X11 display. This isn't used at all, but nevertheless the import fails. We are working to remove skbio from GraftM so this will not be an issue in future.

In the short term, would it be possible to run an X11 forward, like `ssh -X user@server..`? I assume you are running this from a headless server?

**Comment by xvazquezc** [comment] 2016-06-23 03:40
Yes, I was running it from the command line on the remote server. It works doing it as you say. Thanks.

Quick question, I know that my samples are very diverse taxonomically speaking based on previous GraftM runs, but this first sample has given me 7031 OTUs from a total of 7371 reads (sum of number of hits). That is coming from the cluster sequences step.
Is this the usual? I only fed the `singlem pipe` with the forward reads.

**Comment by wwood** [comment] 2016-06-23 03:51
Glad it worked, at last. That sounds like a deep, complex metagenome. For curiosity's sake, what kind of environment is it?

Note that the output of `pipe` is actually 15 different OTU tables, but still, that's quite complex. It seems likely that this is simply just the way the sample is, though. From a developer's point of view, that makes me happy because it shows that singlem is discerning OTUs well. From your perspective though, that sounds like a hard sample to assemble directly, if that is your aim.

**Comment by wwood** [comment] 2016-06-23 03:53
Oh wait I just read that properly. That's from the cluster step? At what clustering threshold?

**Comment by wwood** [comment] 2016-06-23 03:56
The default 97% clustering often does not have much effect in my experience. For reference, I believe a genus-level clustering is at ~88%.

**Comment by xvazquezc** [comment] 2016-06-23 03:58
I used the command from the SingleM front page. This was the log:
```
(mypythonenv)[z3382651@kc07b04 singlem]$ singlem summarise --input_otu_table 028-LFA_otu_table.csv --cluster --clustered_output_otu_table 028-LFA.clustered.otu_table.tsv
06/23/2016 01:04:38 PM INFO: Clustering OTUs with clustering identity 0.967000..
06/23/2016 01:04:39 PM INFO: Finished clustering
06/23/2016 01:04:39 PM INFO: Writing clustered OTU table
06/23/2016 01:04:39 PM INFO: Finished
```

PS: samples are groundwater from a radioactive waste disposal legacy site

**Comment by xvazquezc** [comment] 2016-06-23 04:00
By the way, is the taxonomy based on any database?
GraftM identified many candidate phyla but SingleM doesn't.

**Comment by wwood** [comment] 2016-06-23 04:04
Currently based on IMG. But the choice of database isn't the reason for that difference. The default singlem packages are for ribosomal proteins, where I imagine you ran graftm using a 16S database. There's wayyy more 16S sequences than ribosomal protein sequences known, so you can get better taxonomy from 16S reads, particularly for novel phyla.

**Comment by xvazquezc** [comment] 2016-06-23 04:31
I ran GraftM with the GreenGenes 97% package.
Regarding IMG... you only included seqs from finished genomes, isn't it? I was fiddling a bit with the "find genes" form IMG and by default it only searches in the finished genomes, and many of the candidate divisions are at least recorded as "permanent drafts".

**Comment by wwood** [comment] 2016-06-23 06:09
I believe I included permanent draft genomes. But even if a genome is represented in IMG (and was there when the singlem package was made), the problem remains that the way graftm works is that it assigns reads the taxonomy of nodes that pplacer places it underneath. So in the case of a single genome being in a phyla, no read can be assigned to that phylum because the node above a read from that phyla is 'Bacteria' or 'Archaea', if you follow.

Now, I do have an unpublished 16S SingleM package which might be of use too, potentially getting more resolution on the taxonomies. It isn't online yet but I could dump it somewhere if you were keen.

**Comment by xvazquezc** [comment] 2016-06-23 06:35
I searched in few of the ribosomal protein gpkg that were downloaded with SingleM and I couldn't find any candidate phyla in the `2_taxonomy.csv` files (I guess is where the taxonomy information for each marker is stored...). I have a bit of obsession with this because, again based on GraftM, few of those phyla constitute a fair portion of my community.

So, it would be a problem derived from how the nodes are named in pplacer and how the reads are "inserted" into the tree...

I could give a go to the 16S, especially if the candidate phyla are covered

**Closed** 2016-06-29 07:53 UTC
